name: Publish Jupyter Notebooks as Slides

on:
  push:
    branches:
      - main
    paths:
      - '*.ipynb'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert

    - name: Convert notebooks to slides
      run: |
        mkdir slides
        for notebook in *.ipynb; do
          # Convert each notebook into HTML slides
          jupyter nbconvert --to slides --output "./slides/$(basename ${notebook} .ipynb)" "$notebook"
        done

    - name: Create index.html
      run: |
        # Create index.html that links to all the slides
        echo "<html><body><h1>Slides List: </h1><ul>" > slides/index.html
        for notebook in *.ipynb; do
          # Add a link to each generated slide page in the index
          notebook_name=$(basename "$notebook" .ipynb)
          echo "<li><a href='./${notebook_name}.slides.html'>${notebook_name}</a></li>" >> slides/index.html
        done
        echo "</ul></body></html>" >> slides/index.html

    - name: Deploy slides to GitHub Pages
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout --orphan gh-pages
        git rm -rf .
        mv slides/* .
        git add .
        git commit -m "Publish slides"
        git push -f https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} gh-pages
