name: Publish Jupyter Notebooks as Slides

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert jinja2

    - name: Convert notebooks to slides
      run: |
        mkdir slides
        for notebook in notebooks/*.ipynb; do
          # Convert each notebook into HTML slides
          jupyter nbconvert --to slides --output "../slides/$(basename ${notebook} .ipynb)" "$notebook"
        done

    - name: Create index.html
      run: |
        python scripts/gen.py

    - name: Deploy slides to GitHub Pages
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout --orphan gh-pages
        git rm -rf .
        mv slides/* .
        git add .
        git commit -m "Publish slides"
        git push -f https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} gh-pages
